env: local

rest:
  port: 8081

kafka:
  brokers: localhost:19092
  topics:
    processing-messages: processing-messages
    processed-messages: processing-messages

db:
  host: localhost
  port: 5432
  username: message
  database: message
  password: test
