version: '3'

name: message-service-common

services:
  postgresql:
    image: postgres:16.3
    ports:
      - 5432:5432

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092

  kafka-confluentinc:
    image: confluentinc/cp-kafka:7.6.2

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8080:8080

  message-service:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
