version: '3'

tasks:
  run:local:
    desc: Запустить микросервис сообщений с локальным окружением.
    cmds:
      - go run ./cmd/message/app.go --config_path="./config/local.yaml"

  swag:
    desc: Сгенерировать Swagger-документацию.
    cmds:
      - swag fmt
      - swag init -g ./cmd/message/app.go
